title: A (software) engineering notebook down
email: joshua.dudley.jobs@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Watch another software engineer fall into a deep despair trying to understand how sand thinks better than me
baseurl: ""  # Leave blank for user/organization site. Set to "/REPO_NAME" for project site.
url: "https://dudley2y.github.io"  # no trailing slash

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude folders from the build (like GitHub Actions workflows, etc.)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github