
title: A (software) engineering notebook
email: joshua.dudley.jobs@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Watch another software engineer fall into a deep despair trying to understand how sand thinks better than me
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dudley2y.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  dudley2y
destination: ./_site

# Build settings
theme: minima
plugins:
  - jekyll-feed