name: Jekyll blog deployment 
on: 
push:
  branch: ["gh-pages"]

  workflow_dispatch: 

permissions: 
  content: read
  pages: write  
  id-token: write 

concurrency: 
  group: "pages"
  cancel-in-progress: false 

jobs: 
  # Build job 
  build: 
  runs-on: ubuntu-latest
  steps: 
    - name: Checkout 
      uses: actions/checkout@4
    - name: Setup Pages 
      uses: actions/configure-pages@4
    - name: Build Jekyll 
      uses: actions/jekyll-build-pages@v1
      with: 
        source: ./
        destination: ./_site
  # Deployment job
  deploy: 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    runs-on: ubuntu-latest
    needs: build 
    steps: 
        - name: Deploy to GH-pages
        - id: deployment 
        uses: actions/deploy-pages@v4
